### ISSUE TITLE
demo-4_SEA2019 and plotAnalogSample problem

### ISSUE THREAD

**Issue by arafive** [Weiming-Hu/RAnEnExtra#4]
Hi. I am a PhD student and I am working with statistical tools for weather forecast purposes.

I am learning AnEn with your R codes, but in demo-4 something goes wrong.

```
fcst.id <- which(forecasts$ParameterNames == observations$ParameterNames[config$observation_id])
plotAnalogSample(AnEn, config, i.station = 1, i.test.day = 1,
                 obs.id = config$observation_id, fcst.id = fcst.id, 
                 parameter.names = forecasts$ParameterNames,
                 flts.fraction = 3600, legend.texts = c("Obs","Fcst"))
```
Error in if (length(parameter.names) != dim(forecasts)[1]) { : 
  the argument has zero length

I didn't change anything. This problem is also in Binder.

How can I fix it?

Thanks

**Comment by Weiming-Hu** [comment]
Thanks for reporting this issue. Let me take a look.

**Comment by Weiming-Hu** [comment]
Should be fixed. Please reinstall your `RAnEn` and try again. Thanks.

**Comment by arafive** [comment]
Hi

Unfortunately, the problem still persists the same. I think the problem is
in the RAnEnExtra library. Should I write it on github?

Thanks again

Daniele


Il giorno gio 17 mar 2022 alle ore 20:08 Weiming ***@***.***>
ha scritto:

**Comment by Weiming-Hu** [comment]
That is strange. When I run the binder, it actually worked for me. The issue is the particular tutorial is using an old API, and I actually only changed the tutorial. So you might want to get the updated tutorial code. Sorry about the confusion.

If the issue persists, please copy and paste the error message here again. Thanks.

**Comment by arafive** [comment]
Ok I got it. I substituted the script of demo-4 now it works :)

I just tried it on my pc now, but I think it will be the same on a machine
in my office.

Thanks a lot. Should I close the github issue?

Il gio 17 mar 2022, 21:44 Weiming ***@***.***> ha scritto:

**Comment by Weiming-Hu** [comment]
Closing it for you. By the way, thanks for checking out this project. Feel free to drop a message here if you have any questions or problems.

**Comment by arafive** [comment]
Thanks!

Il gio 17 mar 2022, 22:04 Weiming ***@***.***> ha scritto:
